CHANNEL_IGNORE_LIST = [994901918155542538]
BOOK_EMOJI = "📖"
BONK_EMOJI = "<a:bonk:995996313650999387>"
HARAM_EMOJI = "<a:420:1009446471420096553>"
WICKED_EMOJI = "<:wicked:1012026151218188288>"
QUESTION_EMOJI = "❓"
ASS_EMOJI = "<:ass:1015196306387509328>"
NUMBER_EMOJI_ONE = "1️⃣"
NUMBER_EMOJI_TWO = "2️⃣"
NUMBER_EMOJI_THR = "3️⃣"
NUMBER_EMOJI_FOU = "4️⃣"
NUMBER_EMOJI_FIV = "5️⃣"
NUMBER_EMOJI_SIX = "6️⃣"
NUMBER_EMOJI_SEV = "7️⃣"
NUMBER_EMOJI_EIG = "8️⃣"
NUMBER_EMOJI_NIN = "9️⃣"
NUMBER_EMOJIS = [NUMBER_EMOJI_ONE, NUMBER_EMOJI_TWO, NUMBER_EMOJI_THR, NUMBER_EMOJI_FOU, NUMBER_EMOJI_FIV, NUMBER_EMOJI_SIX, NUMBER_EMOJI_SEV, NUMBER_EMOJI_EIG, NUMBER_EMOJI_NIN]
YES_EMOJI = "✅"
NO_EMOJI = "❌"
REDDIT_USER_AGENT = "Eindjeboss v1.0"
WEATHER_EMOJI_DEFAULT = "🌈"
WEATHER_EMOJI_SUN = "☀"
WEATHER_EMOJI_CLOUDS = "☁"
WEATHER_EMOJI_CLOUDS_RAIN = "🌧"
WEATHER_EMOJI_STORM = "⛈"
WEATHER_EMOJI_SNOW = "❄"
BONK_LEADERBOARD_FILE = "bonk_leaderboard.json"
LAST_BONK_FILE = "last_bonk.json"
PERIODIC_MESSAGES_FILE = "periodic_messages.json"
REMINDER_FILE = "reminders.json"
CAT_SUBREDDITS = ["Cats","Kitten","CatSpotting","IllegallySmolCats","IllegallyBigCats","IllegallyLongCats","Kitty","GrumpyCats","TruckerCats","FromKittenToCat","WetCats","SeniorCats","SleepingCats","Displeased_Kitties","FluffyCats","SuspiciousKitties","CatsCalledFood","catshuggingcats","SadCats","PirateKitties","meowormyson","goodcats","C_AT","thisismylifemeow","pimpcats","fatcats","divorcedcats","notmycat","nowmycat","ChristmasCats","scrungycats","AdorableCats","AliveNamedCats","Medieval_Cats"]
DOG_SUBREDDITS = ["rarepuppers","goldenretrievers","shiba","dogswithjobs","Doggles","dogs","lookatmydog","corgi","WiggleButts","bostonterrier","blop","PuppySmiles","WhatsWrongWithYourDog"]
CAR_SUBREDDITS = ["Porsche", "ferrari", "carporn", "spotted", "JDM", "weirdwheels", "classiccars", "battlecars", "skyline", "itasha", "autos", "audi", "mini", "GT3", "awesomecarmods", "racecarporn", "wec", "super_gt", "rally", "rallyporn"]
BONK_TIMEOUT = 300
BONK_TIMEOUT_SLOW = 14400